//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb.impl;

public class GoTypeImpl implements GO.go_jaxb.GoType, com.sun.xml.bind.JAXBObject, GO.go_jaxb.impl.runtime.UnmarshallableObject, GO.go_jaxb.impl.runtime.XMLSerializable, GO.go_jaxb.impl.runtime.ValidatableObject
{

    protected java.lang.String _Go;
    protected GO.go_jaxb.VersionType _Version;
    protected java.lang.String _Rdf;
    protected GO.go_jaxb.RDFType _RDF;
    public final static java.lang.Class version = (GO.go_jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (GO.go_jaxb.GoType.class);
    }

    public java.lang.String getGo() {
        return _Go;
    }

    public void setGo(java.lang.String value) {
        _Go = value;
    }

    public GO.go_jaxb.VersionType getVersion() {
        return _Version;
    }

    public void setVersion(GO.go_jaxb.VersionType value) {
        _Version = value;
    }

    public java.lang.String getRdf() {
        return _Rdf;
    }

    public void setRdf(java.lang.String value) {
        _Rdf = value;
    }

    public GO.go_jaxb.RDFType getRDF() {
        return _RDF;
    }

    public void setRDF(GO.go_jaxb.RDFType value) {
        _RDF = value;
    }

    public GO.go_jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context) {
        return new GO.go_jaxb.impl.GoTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Version!= null) {
            if (_Version instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Version), "Version");
            } else {
                context.startElement("", "version");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Version), "Version");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Version), "Version");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Version), "Version");
                context.endElement();
            }
        }
        if (_RDF instanceof javax.xml.bind.Element) {
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _RDF), "RDF");
        } else {
            context.startElement("", "RDF");
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _RDF), "RDF");
            context.endNamespaceDecls();
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _RDF), "RDF");
            context.endAttributes();
            context.childAsBody(((com.sun.xml.bind.JAXBObject) _RDF), "RDF");
            context.endElement();
        }
    }

    public void serializeAttributes(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Rdf!= null) {
            context.startAttribute("", "rdf");
            try {
                context.text(((java.lang.String) _Rdf), "Rdf");
            } catch (java.lang.Exception e) {
                GO.go_jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_Go!= null) {
            context.startAttribute("", "go");
            try {
                context.text(((java.lang.String) _Go), "Go");
            } catch (java.lang.Exception e) {
                GO.go_jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (_Version!= null) {
            if (_Version instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Version), "Version");
            }
        }
        if (_RDF instanceof javax.xml.bind.Element) {
            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _RDF), "RDF");
        }
    }

    public void serializeURIs(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Version!= null) {
            if (_Version instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Version), "Version");
            }
        }
        if (_RDF instanceof javax.xml.bind.Element) {
            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _RDF), "RDF");
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (GO.go_jaxb.GoType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava"
+"/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\t|\u00021ppsq\u0000~\u0000\u0000\u0007\u0002\rAppsq\u0000~\u0000\u0000\u0005"
+"6\u0088\u0000ppsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0002\u00e9~\u0082p"
+"psq\u0000~\u0000\b\u0002\u00e9~wsr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psr\u0000\'c"
+"om.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClas"
+"st\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv.grammar.E"
+"lementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000\fcontentM"
+"odelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000\u00cb\u00f9\u00dfq\u0000~\u0000\fp\u0000sq\u0000~\u0000\b\u0000\u00cb\u00f9\u00d4ppsr\u0000 com.sun.msv.gramma"
+"r.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\fpsr\u0000 com.sun.msv.grammar.A"
+"ttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\u000exq\u0000~\u0000\u0003\u0000\u00cb\u00f9\u00c6"
+"q\u0000~\u0000\fpsr\u00002com.sun.msv.grammar.Expression$AnyStringExpression"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bsq\u0000~\u0000\u000b\u0001psr\u0000 com.sun.msv.grammar.AnyName"
+"Class\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000"
+"xpsr\u00000com.sun.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\tq\u0000~\u0000\u0019psr\u0000#com.sun.msv.grammar.SimpleNameClass"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNamet\u0000\u0012Ljava/lang/String;L\u0000\fnamespaceURIq"
+"\u0000~\u0000 xq\u0000~\u0000\u001bt\u0000\u0012GO.go_jaxb.Versiont\u0000+http://java.sun.com/jaxb/x"
+"jc/dummy-elementssq\u0000~\u0000\r\u0002\u001d\u0084\u0096q\u0000~\u0000\fp\u0000sq\u0000~\u0000\u0000\u0002\u001d\u0084\u008bppsq\u0000~\u0000\r\u0000\u00cb\u00f9\u00dfpp\u0000s"
+"q\u0000~\u0000\b\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000\u0012\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\fpsq\u0000~\u0000\u0015\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\fpq\u0000~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq"
+"\u0000~\u0000\u001ft\u0000\u0016GO.go_jaxb.VersionTypeq\u0000~\u0000#sq\u0000~\u0000\b\u0001Q\u008a\u00a7ppsq\u0000~\u0000\u0015\u0001Q\u008a\u009cq\u0000~\u0000"
+"\fpsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/rel"
+"axng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/"
+"util/StringPair;xq\u0000~\u0000\u0003\u0000nCuppsr\u0000\"com.sun.msv.datatype.xsd.Qna"
+"meType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.BuiltinAtomicT"
+"ype\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003"
+"L\u0000\fnamespaceUriq\u0000~\u0000 L\u0000\btypeNameq\u0000~\u0000 L\u0000\nwhiteSpacet\u0000.Lcom/sun"
+"/msv/datatype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org"
+"/2001/XMLSchemat\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpa"
+"ceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd."
+"WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpsr\u00000com.sun.msv.grammar.Expr"
+"ession$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.m"
+"sv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000 L\u0000\fnamespaceUR"
+"Iq\u0000~\u0000 xpq\u0000~\u00009q\u0000~\u00008sq\u0000~\u0000\u001ft\u0000\u0004typet\u0000)http://www.w3.org/2001/XML"
+"Schema-instanceq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0007versiont\u0000\u0000q\u0000~\u0000\u001esq\u0000~\u0000\b\u0002M\typpsq\u0000~"
+"\u0000\r\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000\b\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000\u0012\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\fpsq\u0000~\u0000\u0015\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\fpq\u0000~\u0000\u0018q\u0000"
+"~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u000eGO.go_jaxb.RDFq\u0000~\u0000#sq\u0000~\u0000\r\u0001\u0081\u000f\u0098pp\u0000sq\u0000~\u0000\u0000\u0001\u0081\u000f\u008dp"
+"psq\u0000~\u0000\r\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000\b\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000\u0012\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\fpsq\u0000~\u0000\u0015\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\fpq\u0000"
+"~\u0000\u0018q\u0000~\u0000\u001cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0012GO.go_jaxb.RDFTypeq\u0000~\u0000#sq\u0000~\u0000\b\u0000\u00b5\u0015\u00a9ppsq\u0000"
+"~\u0000\u0015\u0000\u00b5\u0015\u009eq\u0000~\u0000\fpq\u0000~\u00001sq\u0000~\u0000\u001fq\u0000~\u0000Bq\u0000~\u0000Cq\u0000~\u0000\u001esq\u0000~\u0000\u001ft\u0000\u0003RDFq\u0000~\u0000Fsq\u0000~"
+"\u0000\b\u0001\u00cb\u0085<ppsq\u0000~\u0000\u0015\u0001\u00cb\u00851q\u0000~\u0000\fpsr\u0000\u001ccom.sun.msv.grammar.ValueExp\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtq\u0000~\u0000/L\u0000\u0004nameq\u0000~\u00000L\u0000\u0005valuet\u0000\u0012Ljava/lang/Object;xq"
+"\u0000~\u0000\u0003\u0000\u00e1\u00ee\u00afppsr\u0000#com.sun.msv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001"
+"Z\u0000\risAlwaysValidxq\u0000~\u00003q\u0000~\u00008t\u0000\u0006stringsr\u00005com.sun.msv.datatype"
+".xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000;\u0001sq\u0000~\u0000?q\u0000~"
+"\u0000bq\u0000~\u00008t\u0000+http://www.w3.org/1999/02/22-rdf-syntax-ns#sq\u0000~\u0000\u001ft"
+"\u0000\u0003rdfq\u0000~\u0000Fq\u0000~\u0000\u001esq\u0000~\u0000\b\u0002y\u00f4\u00ebppsq\u0000~\u0000\u0015\u0002y\u00f4\u00e0q\u0000~\u0000\fpsq\u0000~\u0000]\u0000\u00e1\u00ee\u00afppq\u0000~\u0000a"
+"q\u0000~\u0000et\u0000(http://www.geneontology.org/dtds/go.dtd#sq\u0000~\u0000\u001ft\u0000\u0002goq"
+"\u0000~\u0000Fq\u0000~\u0000\u001esr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$ClosedHash;x"
+"psr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000"
+"\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000p[\u0000\u0005tablet\u0000![Lcom/sun/msv/"
+"grammar/Expression;xp\u0000\u0000\u0000\u0014\u0000\u0000\u00009pur\u0000![Lcom.sun.msv.grammar.Expr"
+"ession;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppppppppppppppppppppppppppppppppppp"
+"pppq\u0000~\u0000Opq\u0000~\u0000\npppq\u0000~\u0000\u0014q\u0000~\u0000(q\u0000~\u0000Jq\u0000~\u0000Rpppq\u0000~\u0000\tpppq\u0000~\u0000\u0011q\u0000~\u0000\'q\u0000"
+"~\u0000Iq\u0000~\u0000Qq\u0000~\u0000\u0005pppppppppppppppppppq\u0000~\u0000,pppppppppppppq\u0000~\u0000ippppp"
+"pppppppppppppppppppq\u0000~\u0000Gppppppppppppppppppppppppppppppppq\u0000~\u0000"
+"%q\u0000~\u0000\u0006ppppq\u0000~\u0000Vpppq\u0000~\u0000[pppppppppppppq\u0000~\u0000\u0007pppppppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends GO.go_jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "-------------");
        }

        protected Unmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return GO.go_jaxb.impl.GoTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        if (("version" == ___local)&&("" == ___uri)) {
                            _Version = ((GO.go_jaxb.impl.VersionImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.VersionImpl.class), 7, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("version" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 11;
                            return ;
                        }
                        state = 7;
                        continue outer;
                    case  3 :
                        attIdx = context.getAttribute("", "go");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "rdf");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  7 :
                        if (("RDF" == ___local)&&("" == ___uri)) {
                            _RDF = ((GO.go_jaxb.impl.RDFImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.RDFImpl.class), 10, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("RDF" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 8;
                            return ;
                        }
                        break;
                    case  10 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  8 :
                        if (("term" == ___local)&&("" == ___uri)) {
                            _RDF = ((GO.go_jaxb.impl.RDFTypeImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.RDFTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("term" == ___local)&&("" == ___uri)) {
                            _RDF = ((GO.go_jaxb.impl.RDFTypeImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.RDFTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        _RDF = ((GO.go_jaxb.impl.RDFTypeImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.RDFTypeImpl.class), 9, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  11 :
                        attIdx = context.getAttribute("", "timestamp");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Go = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Rdf = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        state = 7;
                        continue outer;
                    case  3 :
                        attIdx = context.getAttribute("", "go");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  12 :
                        if (("version" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 7;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("RDF" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 10;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("", "rdf");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  10 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  8 :
                        _RDF = ((GO.go_jaxb.impl.RDFTypeImpl) spawnChildFromLeaveElement((GO.go_jaxb.impl.RDFTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  11 :
                        attIdx = context.getAttribute("", "timestamp");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  6 :
                        state = 7;
                        continue outer;
                    case  3 :
                        if (("go" == ___local)&&("" == ___uri)) {
                            state = 4;
                            return ;
                        }
                        state = 6;
                        continue outer;
                    case  0 :
                        if (("rdf" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  10 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  8 :
                        _RDF = ((GO.go_jaxb.impl.RDFTypeImpl) spawnChildFromEnterAttribute((GO.go_jaxb.impl.RDFTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  11 :
                        if (("timestamp" == ___local)&&("" == ___uri)) {
                            _Version = ((GO.go_jaxb.impl.VersionTypeImpl) spawnChildFromEnterAttribute((GO.go_jaxb.impl.VersionTypeImpl.class), 12, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  2 :
                        if (("rdf" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                    case  6 :
                        state = 7;
                        continue outer;
                    case  3 :
                        attIdx = context.getAttribute("", "go");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 6;
                            continue outer;
                        }
                        state = 6;
                        continue outer;
                    case  0 :
                        attIdx = context.getAttribute("", "rdf");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText2(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  10 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  5 :
                        if (("go" == ___local)&&("" == ___uri)) {
                            state = 6;
                            return ;
                        }
                        break;
                    case  8 :
                        _RDF = ((GO.go_jaxb.impl.RDFTypeImpl) spawnChildFromLeaveAttribute((GO.go_jaxb.impl.RDFTypeImpl.class), 9, ___uri, ___local, ___qname));
                        return ;
                    case  11 :
                        attIdx = context.getAttribute("", "timestamp");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  4 :
                            eatText1(value);
                            state = 5;
                            return ;
                        case  6 :
                            state = 7;
                            continue outer;
                        case  3 :
                            attIdx = context.getAttribute("", "go");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 6;
                                continue outer;
                            }
                            state = 6;
                            continue outer;
                        case  1 :
                            eatText2(value);
                            state = 2;
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "rdf");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText2(v);
                                state = 3;
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  10 :
                            revertToParentFromText(value);
                            return ;
                        case  8 :
                            _RDF = ((GO.go_jaxb.impl.RDFTypeImpl) spawnChildFromText((GO.go_jaxb.impl.RDFTypeImpl.class), 9, value));
                            return ;
                        case  11 :
                            attIdx = context.getAttribute("", "timestamp");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            _Version = ((GO.go_jaxb.impl.VersionTypeImpl) spawnChildFromText((GO.go_jaxb.impl.VersionTypeImpl.class), 12, value));
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
