//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb.impl;

public class HistoryTypeImpl implements GO.go_jaxb.HistoryType, com.sun.xml.bind.JAXBObject, GO.go_jaxb.impl.runtime.UnmarshallableObject, GO.go_jaxb.impl.runtime.XMLSerializable, GO.go_jaxb.impl.runtime.ValidatableObject
{

    protected java.lang.String _Rationale;
    protected GO.go_jaxb.SplitType _Split;
    protected GO.go_jaxb.MergedType _Merged;
    protected GO.go_jaxb.MovedType _Moved;
    protected java.lang.String _Date;
    protected java.lang.String _Obsolete;
    protected GO.go_jaxb.DeletedType _Deleted;
    protected GO.go_jaxb.CreatedType _Created;
    protected java.lang.String _Person;
    public final static java.lang.Class version = (GO.go_jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (GO.go_jaxb.HistoryType.class);
    }

    public java.lang.String getRationale() {
        return _Rationale;
    }

    public void setRationale(java.lang.String value) {
        _Rationale = value;
    }

    public GO.go_jaxb.SplitType getSplit() {
        return _Split;
    }

    public void setSplit(GO.go_jaxb.SplitType value) {
        _Split = value;
    }

    public GO.go_jaxb.MergedType getMerged() {
        return _Merged;
    }

    public void setMerged(GO.go_jaxb.MergedType value) {
        _Merged = value;
    }

    public GO.go_jaxb.MovedType getMoved() {
        return _Moved;
    }

    public void setMoved(GO.go_jaxb.MovedType value) {
        _Moved = value;
    }

    public java.lang.String getDate() {
        return _Date;
    }

    public void setDate(java.lang.String value) {
        _Date = value;
    }

    public java.lang.String getObsolete() {
        return _Obsolete;
    }

    public void setObsolete(java.lang.String value) {
        _Obsolete = value;
    }

    public GO.go_jaxb.DeletedType getDeleted() {
        return _Deleted;
    }

    public void setDeleted(GO.go_jaxb.DeletedType value) {
        _Deleted = value;
    }

    public GO.go_jaxb.CreatedType getCreated() {
        return _Created;
    }

    public void setCreated(GO.go_jaxb.CreatedType value) {
        _Created = value;
    }

    public java.lang.String getPerson() {
        return _Person;
    }

    public void setPerson(java.lang.String value) {
        _Person = value;
    }

    public GO.go_jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context) {
        return new GO.go_jaxb.impl.HistoryTypeImpl.Unmarshaller(context);
    }

    public void serializeBody(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "date");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Date), "Date");
        } catch (java.lang.Exception e) {
            GO.go_jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "person");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Person), "Person");
        } catch (java.lang.Exception e) {
            GO.go_jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        context.startElement("", "rationale");
        context.endNamespaceDecls();
        context.endAttributes();
        try {
            context.text(((java.lang.String) _Rationale), "Rationale");
        } catch (java.lang.Exception e) {
            GO.go_jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
        }
        context.endElement();
        if (((((_Moved == null)&&(_Created!= null))&&(_Deleted == null))&&(_Merged == null))&&(_Split == null)) {
            if (_Created instanceof javax.xml.bind.Element) {
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Created), "Created");
            } else {
                context.startElement("", "created");
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Created), "Created");
                context.endNamespaceDecls();
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Created), "Created");
                context.endAttributes();
                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Created), "Created");
                context.endElement();
            }
        } else {
            if (((((_Moved == null)&&(_Created == null))&&(_Deleted!= null))&&(_Merged == null))&&(_Split == null)) {
                if (_Deleted instanceof javax.xml.bind.Element) {
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _Deleted), "Deleted");
                } else {
                    context.startElement("", "deleted");
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Deleted), "Deleted");
                    context.endNamespaceDecls();
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Deleted), "Deleted");
                    context.endAttributes();
                    context.childAsBody(((com.sun.xml.bind.JAXBObject) _Deleted), "Deleted");
                    context.endElement();
                }
            } else {
                if (((((_Moved == null)&&(_Created == null))&&(_Deleted == null))&&(_Merged == null))&&(_Split!= null)) {
                    if (_Split instanceof javax.xml.bind.Element) {
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _Split), "Split");
                    } else {
                        context.startElement("", "split");
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Split), "Split");
                        context.endNamespaceDecls();
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Split), "Split");
                        context.endAttributes();
                        context.childAsBody(((com.sun.xml.bind.JAXBObject) _Split), "Split");
                        context.endElement();
                    }
                } else {
                    if (((((_Moved == null)&&(_Created == null))&&(_Deleted == null))&&(_Merged!= null))&&(_Split == null)) {
                        if (_Merged instanceof javax.xml.bind.Element) {
                            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Merged), "Merged");
                        } else {
                            context.startElement("", "merged");
                            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Merged), "Merged");
                            context.endNamespaceDecls();
                            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Merged), "Merged");
                            context.endAttributes();
                            context.childAsBody(((com.sun.xml.bind.JAXBObject) _Merged), "Merged");
                            context.endElement();
                        }
                    } else {
                        if (((((_Moved!= null)&&(_Created == null))&&(_Deleted == null))&&(_Merged == null))&&(_Split == null)) {
                            if (_Moved instanceof javax.xml.bind.Element) {
                                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Moved), "Moved");
                            } else {
                                context.startElement("", "moved");
                                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Moved), "Moved");
                                context.endNamespaceDecls();
                                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Moved), "Moved");
                                context.endAttributes();
                                context.childAsBody(((com.sun.xml.bind.JAXBObject) _Moved), "Moved");
                                context.endElement();
                            }
                        }
                    }
                }
            }
        }
    }

    public void serializeAttributes(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (_Obsolete!= null) {
            context.startAttribute("", "obsolete");
            try {
                context.text(((java.lang.String) _Obsolete), "Obsolete");
            } catch (java.lang.Exception e) {
                GO.go_jaxb.impl.runtime.Util.handlePrintConversionException(this, e, context);
            }
            context.endAttribute();
        }
        if (((((_Moved == null)&&(_Created!= null))&&(_Deleted == null))&&(_Merged == null))&&(_Split == null)) {
            if (_Created instanceof javax.xml.bind.Element) {
                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Created), "Created");
            }
        } else {
            if (((((_Moved == null)&&(_Created == null))&&(_Deleted!= null))&&(_Merged == null))&&(_Split == null)) {
                if (_Deleted instanceof javax.xml.bind.Element) {
                    context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Deleted), "Deleted");
                }
            } else {
                if (((((_Moved == null)&&(_Created == null))&&(_Deleted == null))&&(_Merged == null))&&(_Split!= null)) {
                    if (_Split instanceof javax.xml.bind.Element) {
                        context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Split), "Split");
                    }
                } else {
                    if (((((_Moved == null)&&(_Created == null))&&(_Deleted == null))&&(_Merged!= null))&&(_Split == null)) {
                        if (_Merged instanceof javax.xml.bind.Element) {
                            context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Merged), "Merged");
                        }
                    } else {
                        if (((((_Moved!= null)&&(_Created == null))&&(_Deleted == null))&&(_Merged == null))&&(_Split == null)) {
                            if (_Moved instanceof javax.xml.bind.Element) {
                                context.childAsAttributes(((com.sun.xml.bind.JAXBObject) _Moved), "Moved");
                            }
                        }
                    }
                }
            }
        }
    }

    public void serializeURIs(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        if (((((_Moved == null)&&(_Created!= null))&&(_Deleted == null))&&(_Merged == null))&&(_Split == null)) {
            if (_Created instanceof javax.xml.bind.Element) {
                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Created), "Created");
            }
        } else {
            if (((((_Moved == null)&&(_Created == null))&&(_Deleted!= null))&&(_Merged == null))&&(_Split == null)) {
                if (_Deleted instanceof javax.xml.bind.Element) {
                    context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Deleted), "Deleted");
                }
            } else {
                if (((((_Moved == null)&&(_Created == null))&&(_Deleted == null))&&(_Merged == null))&&(_Split!= null)) {
                    if (_Split instanceof javax.xml.bind.Element) {
                        context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Split), "Split");
                    }
                } else {
                    if (((((_Moved == null)&&(_Created == null))&&(_Deleted == null))&&(_Merged!= null))&&(_Split == null)) {
                        if (_Merged instanceof javax.xml.bind.Element) {
                            context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Merged), "Merged");
                        }
                    } else {
                        if (((((_Moved!= null)&&(_Created == null))&&(_Deleted == null))&&(_Merged == null))&&(_Split == null)) {
                            if (_Moved instanceof javax.xml.bind.Element) {
                                context.childAsURIs(((com.sun.xml.bind.JAXBObject) _Moved), "Moved");
                            }
                        }
                    }
                }
            }
        }
    }

    public java.lang.Class getPrimaryInterface() {
        return (GO.go_jaxb.HistoryType.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.su"
+"n.msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1t\u0000 Lcom/sun/msv/gra"
+"mmar/Expression;L\u0000\u0004exp2q\u0000~\u0000\u0002xr\u0000\u001ecom.sun.msv.grammar.Expressi"
+"on\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilonReducibilityt\u0000\u0013Ljava"
+"/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0002xp\u0019K\u00d5_ppsq\u0000~\u0000\u0000\u0018\u0098E\u00d1ppsq\u0000~\u0000\u0000\b"
+"=\u0094\u0012ppsq\u0000~\u0000\u0000\u0005\b\u00bdFppsr\u0000\'com.sun.msv.grammar.trex.ElementPattern"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000"
+"\u001ecom.sun.msv.grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclare"
+"dAttributesL\u0000\fcontentModelq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0002\u00e0\u00d3\u001fpp\u0000sq\u0000~\u0000\u0000\u0002\u00e0\u00d3\u0014ppsr\u0000\u001b"
+"com.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/d"
+"atatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0002L\u0000\u0004namet\u0000\u001dLcom/sun/msv/util/S"
+"tringPair;xq\u0000~\u0000\u0003\u0000\u00e1\u00ee\u00b8ppsr\u0000#com.sun.msv.datatype.xsd.StringTyp"
+"e\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com.sun.msv.datatype.xsd.Bui"
+"ltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.sun.msv.datatype.xsd.Concre"
+"teType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.datatype.xsd.XSDatatypeImpl"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/lang/String;L\u0000\btypeNameq\u0000"
+"~\u0000\u0016L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/datatype/xsd/WhiteSpaceProce"
+"ssor;xpt\u0000 http://www.w3.org/2001/XMLSchemat\u0000\u0006stringsr\u00005com.s"
+"un.msv.datatype.xsd.WhiteSpaceProcessor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"r\u0000,com.sun.msv.datatype.xsd.WhiteSpaceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp"
+"\u0001sr\u00000com.sun.msv.grammar.Expression$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.util.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000"
+"\tlocalNameq\u0000~\u0000\u0016L\u0000\fnamespaceURIq\u0000~\u0000\u0016xpq\u0000~\u0000\u001aq\u0000~\u0000\u0019sr\u0000\u001dcom.sun.m"
+"sv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0001\u0001\u00fe\u00e4Wppsr\u0000 com.sun.msv.g"
+"rammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003expq\u0000~\u0000\u0002L\u0000\tnameClassq\u0000~\u0000\nxq"
+"\u0000~\u0000\u0003\u0001\u00fe\u00e4Lsr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u000e\u0000n"
+"Cuppsr\u0000\"com.sun.msv.datatype.xsd.QnameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0013q"
+"\u0000~\u0000\u0019t\u0000\u0005QNamesr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProcessor"
+"$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001cq\u0000~\u0000\u001fsq\u0000~\u0000 q\u0000~\u0000+q\u0000~\u0000\u0019sr\u0000#com.sun.m"
+"sv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0016L\u0000\fnam"
+"espaceURIq\u0000~\u0000\u0016xr\u0000\u001dcom.sun.msv.grammar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp"
+"t\u0000\u0004typet\u0000)http://www.w3.org/2001/XMLSchema-instancesr\u00000com.s"
+"un.msv.grammar.Expression$EpsilonExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003"
+"\u0000\u0000\u0000\tsq\u0000~\u0000&\u0001psq\u0000~\u0000/t\u0000\u0004datet\u0000\u0000sq\u0000~\u0000\t\u0002\'\u00ea\"pp\u0000sq\u0000~\u0000\u0000\u0002\'\u00ea\u0017ppq\u0000~\u0000\u0011sq"
+"\u0000~\u0000\"\u0001E\u00fbZppsq\u0000~\u0000$\u0001E\u00fbOq\u0000~\u0000\'pq\u0000~\u0000(sq\u0000~\u0000/q\u0000~\u00002q\u0000~\u00003q\u0000~\u00005sq\u0000~\u0000/t\u0000"
+"\u0006personq\u0000~\u00009sq\u0000~\u0000\t\u00034\u00d6\u00c7pp\u0000sq\u0000~\u0000\u0000\u00034\u00d6\u00bcppq\u0000~\u0000\u0011sq\u0000~\u0000\"\u0002R\u00e7\u00ffppsq\u0000~\u0000$"
+"\u0002R\u00e7\u00f4q\u0000~\u0000\'pq\u0000~\u0000(sq\u0000~\u0000/q\u0000~\u00002q\u0000~\u00003q\u0000~\u00005sq\u0000~\u0000/t\u0000\trationaleq\u0000~\u00009s"
+"q\u0000~\u0000\"\u0010Z\u00b1\u00bappsq\u0000~\u0000\"\u000eK\u001a\u00c2ppsq\u0000~\u0000\"\r\u007f \u00e1ppsq\u0000~\u0000\"\n\u009db\u00feppsq\u0000~\u0000\"\t\u00d1i\u001dpps"
+"q\u0000~\u0000\"\u0007\u00bcQ\u0087ppsq\u0000~\u0000\"\u0006\u00f0W\u00a6ppsq\u0000~\u0000\"\u0004Gw\u00cbppsq\u0000~\u0000\"\u0003{}\u00eappsq\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000"
+"sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4ppsr\u0000 com.sun.msv.grammar.OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000x"
+"r\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0002xq\u0000~\u0000\u0003\u0000"
+"\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'psr\u00002com.sun.msv.grammar.Expression$"
+"AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0003\u0000\u0000\u0000\bq\u0000~\u00006psr\u0000 com.sun.ms"
+"v.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u00000q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0012GO.go_j"
+"axb.Createdt\u0000+http://java.sun.com/jaxb/xjc/dummy-elementssq\u0000"
+"~\u0000\t\u0002\u00af\u0084\tpp\u0000sq\u0000~\u0000\u0000\u0002\u00af\u0083\u00feppsq\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~"
+"\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq\u0000~\u00005sq\u0000~\u0000/t\u0000\u0016GO.go_jaxb.Create"
+"dTypeq\u0000~\u0000]sq\u0000~\u0000\"\u0001\u00e3\u008a\u001appsq\u0000~\u0000$\u0001\u00e3\u008a\u000fq\u0000~\u0000\'pq\u0000~\u0000(sq\u0000~\u0000/q\u0000~\u00002q\u0000~\u00003q"
+"\u0000~\u00005sq\u0000~\u0000/t\u0000\u0007createdq\u0000~\u00009sq\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9"
+"q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq\u0000~\u00005sq\u0000~\u0000/t\u0000\u0012GO.go_jaxb.Del"
+"etedq\u0000~\u0000]sq\u0000~\u0000\t\u0002\u00a8\u00df\u00d9pp\u0000sq\u0000~\u0000\u0000\u0002\u00a8\u00df\u00ceppsq\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4pps"
+"q\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq\u0000~\u00005sq\u0000~\u0000/t\u0000\u0016GO.go"
+"_jaxb.DeletedTypeq\u0000~\u0000]sq\u0000~\u0000\"\u0001\u00dc\u00e5\u00eappsq\u0000~\u0000$\u0001\u00dc\u00e5\u00dfq\u0000~\u0000\'pq\u0000~\u0000(sq\u0000~\u0000"
+"/q\u0000~\u00002q\u0000~\u00003q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0007deletedq\u0000~\u00009sq\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4"
+"ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq\u0000~\u00005sq\u0000~\u0000/t\u0000\u0010GO"
+".go_jaxb.Splitq\u0000~\u0000]sq\u0000~\u0000\t\u0002\u0015\u0017\u0094pp\u0000sq\u0000~\u0000\u0000\u0002\u0015\u0017\u0089ppsq\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000"
+"~\u0000\"\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq\u0000~\u00005sq\u0000~"
+"\u0000/t\u0000\u0014GO.go_jaxb.SplitTypeq\u0000~\u0000]sq\u0000~\u0000\"\u0001I\u001d\u00a5ppsq\u0000~\u0000$\u0001I\u001d\u009aq\u0000~\u0000\'pq\u0000"
+"~\u0000(sq\u0000~\u0000/q\u0000~\u00002q\u0000~\u00003q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0005splitq\u0000~\u00009sq\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~"
+"\u0000\"\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq\u0000~\u00005sq\u0000~\u0000"
+"/t\u0000\u0011GO.go_jaxb.Mergedq\u0000~\u0000]sq\u0000~\u0000\t\u0002\u00e1\u00bd\u00e1pp\u0000sq\u0000~\u0000\u0000\u0002\u00e1\u00bd\u00d6ppsq\u0000~\u0000\t\u0000\u00cb\u00f9"
+"\u00dfpp\u0000sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq\u0000"
+"~\u00005sq\u0000~\u0000/t\u0000\u0015GO.go_jaxb.MergedTypeq\u0000~\u0000]sq\u0000~\u0000\"\u0002\u0015\u00c3\u00f2ppsq\u0000~\u0000$\u0002\u0015\u00c3\u00e7"
+"q\u0000~\u0000\'pq\u0000~\u0000(sq\u0000~\u0000/q\u0000~\u00002q\u0000~\u00003q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0006mergedq\u0000~\u00009sq\u0000~\u0000\t\u0000\u00cb"
+"\u00f9\u00dfpp\u0000sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000Xq\u0000~\u0000Zq"
+"\u0000~\u00005sq\u0000~\u0000/t\u0000\u0010GO.go_jaxb.Movedq\u0000~\u0000]sq\u0000~\u0000\t\u0002\u000f\u0096\u00f6pp\u0000sq\u0000~\u0000\u0000\u0002\u000f\u0096\u00ebpps"
+"q\u0000~\u0000\t\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000\"\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000S\u0000\u00cb\u00f9\u00c9q\u0000~\u0000\'psq\u0000~\u0000$\u0000\u00cb\u00f9\u00c6q\u0000~\u0000\'pq\u0000~\u0000"
+"Xq\u0000~\u0000Zq\u0000~\u00005sq\u0000~\u0000/t\u0000\u0014GO.go_jaxb.MovedTypeq\u0000~\u0000]sq\u0000~\u0000\"\u0001C\u009d\u0007ppsq\u0000"
+"~\u0000$\u0001C\u009c\u00fcq\u0000~\u0000\'pq\u0000~\u0000(sq\u0000~\u0000/q\u0000~\u00002q\u0000~\u00003q\u0000~\u00005sq\u0000~\u0000/t\u0000\u0005movedq\u0000~\u00009sq"
+"\u0000~\u0000\"\u0000\u00b3\u008f\u0089ppsq\u0000~\u0000$\u0000\u00b3\u008f~q\u0000~\u0000\'psq\u0000~\u0000\u000e\u0000J~\u0006ppsr\u0000)com.sun.msv.dataty"
+"pe.xsd.EnumerationFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0006valuest\u0000\u000fLjava/util/Set"
+";xr\u00009com.sun.msv.datatype.xsd.DataTypeWithValueConstraintFac"
+"et\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.datatype.xsd.DataTypeWithFacet\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needValueCheckFlagL\u0000\bbaseTypet\u0000)"
+"Lcom/sun/msv/datatype/xsd/XSDatatypeImpl;L\u0000\fconcreteTypet\u0000\'L"
+"com/sun/msv/datatype/xsd/ConcreteType;L\u0000\tfacetNameq\u0000~\u0000\u0016xq\u0000~\u0000"
+"\u0015q\u0000~\u00009pq\u0000~\u0000-\u0000\u0000sr\u0000$com.sun.msv.datatype.xsd.NmtokenType\u0000\u0000\u0000\u0000\u0000\u0000"
+"\u0000\u0001\u0002\u0000\u0000xr\u0000\"com.sun.msv.datatype.xsd.TokenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0012"
+"q\u0000~\u0000\u0019t\u0000\u0007NMTOKENq\u0000~\u0000-\u0000q\u0000~\u0000\u00c3t\u0000\u000benumerationsr\u0000\u0011java.util.HashSe"
+"t\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0002not\u0000\u0003yesxq\u0000~\u0000\u001fsq\u0000~\u0000 t\u0000\u000fNMTOKE"
+"N-derivedq\u0000~\u00009sq\u0000~\u0000/t\u0000\bobsoleteq\u0000~\u00009q\u0000~\u00005sr\u0000\"com.sun.msv.gra"
+"mmar.ExpressionPool\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/gra"
+"mmar/ExpressionPool$ClosedHash;xpsr\u0000-com.sun.msv.grammar.Exp"
+"ressionPool$ClosedHash\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006pare"
+"ntq\u0000~\u0000\u00cf[\u0000\u0005tablet\u0000![Lcom/sun/msv/grammar/Expression;xp\u0000\u0000\u00002\u0000\u0000\u0000"
+"9pur\u0000![Lcom.sun.msv.grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppp"
+"pq\u0000~\u0000<pppppq\u0000~\u0000Pppppppppq\u0000~\u0000;pq\u0000~\u0000Jpppppppppppppq\u0000~\u0000\u0098ppppppp"
+"pq\u0000~\u0000Uq\u0000~\u0000bq\u0000~\u0000mq\u0000~\u0000uq\u0000~\u0000\u0080q\u0000~\u0000fq\u0000~\u0000\u0088q\u0000~\u0000\u0093q\u0000~\u0000\u009bq\u0000~\u0000\u00a6q\u0000~\u0000\u00aeq\u0000~\u0000"
+"Rq\u0000~\u0000aq\u0000~\u0000lq\u0000~\u0000tq\u0000~\u0000\u007fq\u0000~\u0000\u0087q\u0000~\u0000\u0092q\u0000~\u0000\u009aq\u0000~\u0000\u00a5q\u0000~\u0000Nq\u0000~\u0000\u00adq\u0000~\u0000\u008cq\u0000~\u0000"
+"Hq\u0000~\u0000\u00b2ppppppppppq\u0000~\u0000Oq\u0000~\u0000\u0007ppppppq\u0000~\u0000#ppq\u0000~\u0000Cq\u0000~\u0000yq\u0000~\u0000Ipq\u0000~\u0000L"
+"pppppppq\u0000~\u0000\rppq\u0000~\u0000Bpppppppppppppppq\u0000~\u0000_ppppppppppq\u0000~\u0000\u0005q\u0000~\u0000Mp"
+"pppq\u0000~\u0000\u0085q\u0000~\u0000\u0006q\u0000~\u0000\u00abppppppppq\u0000~\u0000\bppppq\u0000~\u0000\u009fpppppppq\u0000~\u0000rq\u0000~\u0000Kppp"
+"pppppppppppq\u0000~\u0000\u00b7ppppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends GO.go_jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "------------------------");
        }

        protected Unmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return GO.go_jaxb.impl.HistoryTypeImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  20 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  16 :
                        _Created = ((GO.go_jaxb.impl.CreatedTypeImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.CreatedTypeImpl.class), 17, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  22 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  14 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  13 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  12 :
                        if (("created" == ___local)&&("" == ___uri)) {
                            _Created = ((GO.go_jaxb.impl.CreatedImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.CreatedImpl.class), 13, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("created" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 16;
                            return ;
                        }
                        if (("deleted" == ___local)&&("" == ___uri)) {
                            _Deleted = ((GO.go_jaxb.impl.DeletedImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.DeletedImpl.class), 13, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("deleted" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 18;
                            return ;
                        }
                        if (("split" == ___local)&&("" == ___uri)) {
                            _Split = ((GO.go_jaxb.impl.SplitImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.SplitImpl.class), 13, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("split" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 20;
                            return ;
                        }
                        if (("merged" == ___local)&&("" == ___uri)) {
                            _Merged = ((GO.go_jaxb.impl.MergedImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.MergedImpl.class), 13, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("merged" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 14;
                            return ;
                        }
                        if (("moved" == ___local)&&("" == ___uri)) {
                            _Moved = ((GO.go_jaxb.impl.MovedImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.MovedImpl.class), 13, ___uri, ___local, ___qname, __atts));
                            return ;
                        }
                        if (("moved" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 22;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("", "obsolete");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  18 :
                        _Deleted = ((GO.go_jaxb.impl.DeletedTypeImpl) spawnChildFromEnterElement((GO.go_jaxb.impl.DeletedTypeImpl.class), 19, ___uri, ___local, ___qname, __atts));
                        return ;
                    case  6 :
                        if (("person" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 7;
                            return ;
                        }
                        break;
                    case  3 :
                        if (("date" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 4;
                            return ;
                        }
                        break;
                    case  9 :
                        if (("rationale" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, true);
                            state = 10;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        private void eatText1(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Obsolete = com.sun.xml.bind.WhiteSpaceProcessor.collapse(value);
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  20 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  11 :
                        if (("rationale" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 12;
                            return ;
                        }
                        break;
                    case  16 :
                        _Created = ((GO.go_jaxb.impl.CreatedTypeImpl) spawnChildFromLeaveElement((GO.go_jaxb.impl.CreatedTypeImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  22 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  14 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  13 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  23 :
                        if (("moved" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 13;
                            return ;
                        }
                        break;
                    case  0 :
                        attIdx = context.getAttribute("", "obsolete");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  17 :
                        if (("created" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 13;
                            return ;
                        }
                        break;
                    case  18 :
                        _Deleted = ((GO.go_jaxb.impl.DeletedTypeImpl) spawnChildFromLeaveElement((GO.go_jaxb.impl.DeletedTypeImpl.class), 19, ___uri, ___local, ___qname));
                        return ;
                    case  5 :
                        if (("date" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 6;
                            return ;
                        }
                        break;
                    case  19 :
                        if (("deleted" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 13;
                            return ;
                        }
                        break;
                    case  8 :
                        if (("person" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 9;
                            return ;
                        }
                        break;
                    case  15 :
                        if (("merged" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 13;
                            return ;
                        }
                        break;
                    case  21 :
                        if (("split" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 13;
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  20 :
                        if (("resource" == ___local)&&("" == ___uri)) {
                            _Split = ((GO.go_jaxb.impl.SplitTypeImpl) spawnChildFromEnterAttribute((GO.go_jaxb.impl.SplitTypeImpl.class), 21, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                    case  16 :
                        _Created = ((GO.go_jaxb.impl.CreatedTypeImpl) spawnChildFromEnterAttribute((GO.go_jaxb.impl.CreatedTypeImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  22 :
                        if (("resource" == ___local)&&("" == ___uri)) {
                            _Moved = ((GO.go_jaxb.impl.MovedTypeImpl) spawnChildFromEnterAttribute((GO.go_jaxb.impl.MovedTypeImpl.class), 23, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                    case  14 :
                        if (("resource" == ___local)&&("" == ___uri)) {
                            _Merged = ((GO.go_jaxb.impl.MergedTypeImpl) spawnChildFromEnterAttribute((GO.go_jaxb.impl.MergedTypeImpl.class), 15, ___uri, ___local, ___qname));
                            return ;
                        }
                        break;
                    case  13 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        if (("obsolete" == ___local)&&("" == ___uri)) {
                            state = 1;
                            return ;
                        }
                        state = 3;
                        continue outer;
                    case  18 :
                        _Deleted = ((GO.go_jaxb.impl.DeletedTypeImpl) spawnChildFromEnterAttribute((GO.go_jaxb.impl.DeletedTypeImpl.class), 19, ___uri, ___local, ___qname));
                        return ;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  20 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  16 :
                        _Created = ((GO.go_jaxb.impl.CreatedTypeImpl) spawnChildFromLeaveAttribute((GO.go_jaxb.impl.CreatedTypeImpl.class), 17, ___uri, ___local, ___qname));
                        return ;
                    case  22 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  14 :
                        attIdx = context.getAttribute("", "resource");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                    case  13 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  0 :
                        attIdx = context.getAttribute("", "obsolete");
                        if (attIdx >= 0) {
                            final java.lang.String v = context.eatAttribute(attIdx);
                            eatText1(v);
                            state = 3;
                            continue outer;
                        }
                        state = 3;
                        continue outer;
                    case  18 :
                        _Deleted = ((GO.go_jaxb.impl.DeletedTypeImpl) spawnChildFromLeaveAttribute((GO.go_jaxb.impl.DeletedTypeImpl.class), 19, ___uri, ___local, ___qname));
                        return ;
                    case  2 :
                        if (("obsolete" == ___local)&&("" == ___uri)) {
                            state = 3;
                            return ;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  20 :
                            attIdx = context.getAttribute("", "resource");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  16 :
                            _Created = ((GO.go_jaxb.impl.CreatedTypeImpl) spawnChildFromText((GO.go_jaxb.impl.CreatedTypeImpl.class), 17, value));
                            return ;
                        case  22 :
                            attIdx = context.getAttribute("", "resource");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  14 :
                            attIdx = context.getAttribute("", "resource");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                        case  13 :
                            revertToParentFromText(value);
                            return ;
                        case  10 :
                            eatText2(value);
                            state = 11;
                            return ;
                        case  0 :
                            attIdx = context.getAttribute("", "obsolete");
                            if (attIdx >= 0) {
                                final java.lang.String v = context.eatAttribute(attIdx);
                                eatText1(v);
                                state = 3;
                                continue outer;
                            }
                            state = 3;
                            continue outer;
                        case  7 :
                            eatText3(value);
                            state = 8;
                            return ;
                        case  18 :
                            _Deleted = ((GO.go_jaxb.impl.DeletedTypeImpl) spawnChildFromText((GO.go_jaxb.impl.DeletedTypeImpl.class), 19, value));
                            return ;
                        case  4 :
                            eatText4(value);
                            state = 5;
                            return ;
                        case  1 :
                            eatText1(value);
                            state = 2;
                            return ;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

        private void eatText2(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Rationale = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText3(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Person = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

        private void eatText4(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            try {
                _Date = value;
            } catch (java.lang.Exception e) {
                handleParseConversionException(e);
            }
        }

    }

}
