//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb.impl;

public class HistoryImpl
    extends GO.go_jaxb.impl.HistoryTypeImpl
    implements GO.go_jaxb.History, com.sun.xml.bind.RIElement, com.sun.xml.bind.JAXBObject, GO.go_jaxb.impl.runtime.UnmarshallableObject, GO.go_jaxb.impl.runtime.XMLSerializable, GO.go_jaxb.impl.runtime.ValidatableObject
{

    public final static java.lang.Class version = (GO.go_jaxb.impl.JAXBVersion.class);
    private static com.sun.msv.grammar.Grammar schemaFragment;

    private final static java.lang.Class PRIMARY_INTERFACE_CLASS() {
        return (GO.go_jaxb.History.class);
    }

    public java.lang.String ____jaxb_ri____getNamespaceURI() {
        return "";
    }

    public java.lang.String ____jaxb_ri____getLocalName() {
        return "history";
    }

    public GO.go_jaxb.impl.runtime.UnmarshallingEventHandler createUnmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context) {
        return new GO.go_jaxb.impl.HistoryImpl.Unmarshaller(context);
    }

    public void serializeBody(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
        context.startElement("", "history");
        super.serializeURIs(context);
        context.endNamespaceDecls();
        super.serializeAttributes(context);
        context.endAttributes();
        super.serializeBody(context);
        context.endElement();
    }

    public void serializeAttributes(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public void serializeURIs(GO.go_jaxb.impl.runtime.XMLSerializer context)
        throws org.xml.sax.SAXException
    {
    }

    public java.lang.Class getPrimaryInterface() {
        return (GO.go_jaxb.History.class);
    }

    public com.sun.msv.verifier.DocumentDeclaration createRawValidator() {
        if (schemaFragment == null) {
            schemaFragment = com.sun.xml.bind.validator.SchemaDeserializer.deserialize((
 "\u00ac\u00ed\u0000\u0005sr\u0000\'com.sun.msv.grammar.trex.ElementPattern\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000"
+"\tnameClasst\u0000\u001fLcom/sun/msv/grammar/NameClass;xr\u0000\u001ecom.sun.msv."
+"grammar.ElementExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002Z\u0000\u001aignoreUndeclaredAttributesL\u0000"
+"\fcontentModelt\u0000 Lcom/sun/msv/grammar/Expression;xr\u0000\u001ecom.sun."
+"msv.grammar.Expression\u00f8\u0018\u0082\u00e8N5~O\u0002\u0000\u0003I\u0000\u000ecachedHashCodeL\u0000\u0013epsilon"
+"Reducibilityt\u0000\u0013Ljava/lang/Boolean;L\u0000\u000bexpandedExpq\u0000~\u0000\u0003xp\u001b\u00ac\u00e7\u0092p"
+"p\u0000sr\u0000\u001fcom.sun.msv.grammar.SequenceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001dcom.sun."
+"msv.grammar.BinaryExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0004exp1q\u0000~\u0000\u0003L\u0000\u0004exp2q\u0000~\u0000\u0003xq\u0000~"
+"\u0000\u0004\u001b\u00ac\u00e7\u0087ppsq\u0000~\u0000\u0007\u0019K\u00d5_ppsq\u0000~\u0000\u0007\u0018\u0098E\u00d1ppsq\u0000~\u0000\u0007\b=\u0094\u0012ppsq\u0000~\u0000\u0007\u0005\b\u00bdFppsq\u0000~"
+"\u0000\u0000\u0002\u00e0\u00d3\u001fpp\u0000sq\u0000~\u0000\u0007\u0002\u00e0\u00d3\u0014ppsr\u0000\u001bcom.sun.msv.grammar.DataExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001"
+"\u0002\u0000\u0003L\u0000\u0002dtt\u0000\u001fLorg/relaxng/datatype/Datatype;L\u0000\u0006exceptq\u0000~\u0000\u0003L\u0000\u0004n"
+"amet\u0000\u001dLcom/sun/msv/util/StringPair;xq\u0000~\u0000\u0004\u0000\u00e1\u00ee\u00b8ppsr\u0000#com.sun.m"
+"sv.datatype.xsd.StringType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001Z\u0000\risAlwaysValidxr\u0000*com"
+".sun.msv.datatype.xsd.BuiltinAtomicType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000%com.su"
+"n.msv.datatype.xsd.ConcreteType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\'com.sun.msv.da"
+"tatype.xsd.XSDatatypeImpl\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0003L\u0000\fnamespaceUrit\u0000\u0012Ljava/"
+"lang/String;L\u0000\btypeNameq\u0000~\u0000\u0018L\u0000\nwhiteSpacet\u0000.Lcom/sun/msv/dat"
+"atype/xsd/WhiteSpaceProcessor;xpt\u0000 http://www.w3.org/2001/XM"
+"LSchemat\u0000\u0006stringsr\u00005com.sun.msv.datatype.xsd.WhiteSpaceProce"
+"ssor$Preserve\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000,com.sun.msv.datatype.xsd.WhiteSp"
+"aceProcessor\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xp\u0001sr\u00000com.sun.msv.grammar.Expression"
+"$NullSetExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\nppsr\u0000\u001bcom.sun.msv.uti"
+"l.StringPair\u00d0t\u001ejB\u008f\u008d\u00a0\u0002\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq\u0000~\u0000\u0018"
+"xpq\u0000~\u0000\u001cq\u0000~\u0000\u001bsr\u0000\u001dcom.sun.msv.grammar.ChoiceExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~"
+"\u0000\b\u0001\u00fe\u00e4Wppsr\u0000 com.sun.msv.grammar.AttributeExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0002L\u0000\u0003ex"
+"pq\u0000~\u0000\u0003L\u0000\tnameClassq\u0000~\u0000\u0001xq\u0000~\u0000\u0004\u0001\u00fe\u00e4Lsr\u0000\u0011java.lang.Boolean\u00cd r\u0080\u00d5\u009c"
+"\u00fa\u00ee\u0002\u0000\u0001Z\u0000\u0005valuexp\u0000psq\u0000~\u0000\u0010\u0000nCuppsr\u0000\"com.sun.msv.datatype.xsd.Qn"
+"ameType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0015q\u0000~\u0000\u001bt\u0000\u0005QNamesr\u00005com.sun.msv.datatyp"
+"e.xsd.WhiteSpaceProcessor$Collapse\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u001eq\u0000~\u0000!sq\u0000~"
+"\u0000\"q\u0000~\u0000-q\u0000~\u0000\u001bsr\u0000#com.sun.msv.grammar.SimpleNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002"
+"\u0000\u0002L\u0000\tlocalNameq\u0000~\u0000\u0018L\u0000\fnamespaceURIq\u0000~\u0000\u0018xr\u0000\u001dcom.sun.msv.gramm"
+"ar.NameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xpt\u0000\u0004typet\u0000)http://www.w3.org/2001/XM"
+"LSchema-instancesr\u00000com.sun.msv.grammar.Expression$EpsilonEx"
+"pression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0004\u0000\u0000\u0000\tsq\u0000~\u0000(\u0001psq\u0000~\u00001t\u0000\u0004datet\u0000\u0000sq\u0000~\u0000\u0000\u0002"
+"\'\u00ea\"pp\u0000sq\u0000~\u0000\u0007\u0002\'\u00ea\u0017ppq\u0000~\u0000\u0013sq\u0000~\u0000$\u0001E\u00fbZppsq\u0000~\u0000&\u0001E\u00fbOq\u0000~\u0000)pq\u0000~\u0000*sq\u0000~"
+"\u00001q\u0000~\u00004q\u0000~\u00005q\u0000~\u00007sq\u0000~\u00001t\u0000\u0006personq\u0000~\u0000;sq\u0000~\u0000\u0000\u00034\u00d6\u00c7pp\u0000sq\u0000~\u0000\u0007\u00034\u00d6\u00bc"
+"ppq\u0000~\u0000\u0013sq\u0000~\u0000$\u0002R\u00e7\u00ffppsq\u0000~\u0000&\u0002R\u00e7\u00f4q\u0000~\u0000)pq\u0000~\u0000*sq\u0000~\u00001q\u0000~\u00004q\u0000~\u00005q\u0000~\u0000"
+"7sq\u0000~\u00001t\u0000\trationaleq\u0000~\u0000;sq\u0000~\u0000$\u0010Z\u00b1\u00bappsq\u0000~\u0000$\u000eK\u001a\u00c2ppsq\u0000~\u0000$\r\u007f \u00e1pp"
+"sq\u0000~\u0000$\n\u009db\u00feppsq\u0000~\u0000$\t\u00d1i\u001dppsq\u0000~\u0000$\u0007\u00bcQ\u0087ppsq\u0000~\u0000$\u0006\u00f0W\u00a6ppsq\u0000~\u0000$\u0004Gw\u00cbpp"
+"sq\u0000~\u0000$\u0003{}\u00eappsq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsr\u0000 com.sun.msv.grammar"
+".OneOrMoreExp\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\u001ccom.sun.msv.grammar.UnaryExp\u0000\u0000\u0000\u0000"
+"\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\u0003expq\u0000~\u0000\u0003xq\u0000~\u0000\u0004\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)psr\u00002com.su"
+"n.msv.grammar.Expression$AnyStringExpression\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000"
+"\u0004\u0000\u0000\u0000\bq\u0000~\u00008psr\u0000 com.sun.msv.grammar.AnyNameClass\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq"
+"\u0000~\u00002q\u0000~\u00007sq\u0000~\u00001t\u0000\u0012GO.go_jaxb.Createdt\u0000+http://java.sun.com/j"
+"axb/xjc/dummy-elementssq\u0000~\u0000\u0000\u0002\u00af\u0084\tpp\u0000sq\u0000~\u0000\u0007\u0002\u00af\u0083\u00feppsq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000"
+"sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)pq\u0000~\u0000Zq\u0000~\u0000\\q\u0000~\u00007s"
+"q\u0000~\u00001t\u0000\u0016GO.go_jaxb.CreatedTypeq\u0000~\u0000_sq\u0000~\u0000$\u0001\u00e3\u008a\u001appsq\u0000~\u0000&\u0001\u00e3\u008a\u000fq\u0000~"
+"\u0000)pq\u0000~\u0000*sq\u0000~\u00001q\u0000~\u00004q\u0000~\u00005q\u0000~\u00007sq\u0000~\u00001t\u0000\u0007createdq\u0000~\u0000;sq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00df"
+"pp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)pq\u0000~\u0000Zq\u0000~\u0000\\q\u0000~"
+"\u00007sq\u0000~\u00001t\u0000\u0012GO.go_jaxb.Deletedq\u0000~\u0000_sq\u0000~\u0000\u0000\u0002\u00a8\u00df\u00d9pp\u0000sq\u0000~\u0000\u0007\u0002\u00a8\u00df\u00cepps"
+"q\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)pq\u0000~\u0000"
+"Zq\u0000~\u0000\\q\u0000~\u00007sq\u0000~\u00001t\u0000\u0016GO.go_jaxb.DeletedTypeq\u0000~\u0000_sq\u0000~\u0000$\u0001\u00dc\u00e5\u00eapps"
+"q\u0000~\u0000&\u0001\u00dc\u00e5\u00dfq\u0000~\u0000)pq\u0000~\u0000*sq\u0000~\u00001q\u0000~\u00004q\u0000~\u00005q\u0000~\u00007sq\u0000~\u00001t\u0000\u0007deletedq\u0000~"
+"\u0000;sq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)pq"
+"\u0000~\u0000Zq\u0000~\u0000\\q\u0000~\u00007sq\u0000~\u00001t\u0000\u0010GO.go_jaxb.Splitq\u0000~\u0000_sq\u0000~\u0000\u0000\u0002\u0015\u0017\u0094pp\u0000sq\u0000"
+"~\u0000\u0007\u0002\u0015\u0017\u0089ppsq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6"
+"q\u0000~\u0000)pq\u0000~\u0000Zq\u0000~\u0000\\q\u0000~\u00007sq\u0000~\u00001t\u0000\u0014GO.go_jaxb.SplitTypeq\u0000~\u0000_sq\u0000~\u0000"
+"$\u0001I\u001d\u00a5ppsq\u0000~\u0000&\u0001I\u001d\u009aq\u0000~\u0000)pq\u0000~\u0000*sq\u0000~\u00001q\u0000~\u00004q\u0000~\u00005q\u0000~\u00007sq\u0000~\u00001t\u0000\u0005sp"
+"litq\u0000~\u0000;sq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q"
+"\u0000~\u0000)pq\u0000~\u0000Zq\u0000~\u0000\\q\u0000~\u00007sq\u0000~\u00001t\u0000\u0011GO.go_jaxb.Mergedq\u0000~\u0000_sq\u0000~\u0000\u0000\u0002\u00e1\u00bd"
+"\u00e1pp\u0000sq\u0000~\u0000\u0007\u0002\u00e1\u00bd\u00d6ppsq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq\u0000"
+"~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)pq\u0000~\u0000Zq\u0000~\u0000\\q\u0000~\u00007sq\u0000~\u00001t\u0000\u0015GO.go_jaxb.MergedTypeq\u0000"
+"~\u0000_sq\u0000~\u0000$\u0002\u0015\u00c3\u00f2ppsq\u0000~\u0000&\u0002\u0015\u00c3\u00e7q\u0000~\u0000)pq\u0000~\u0000*sq\u0000~\u00001q\u0000~\u00004q\u0000~\u00005q\u0000~\u00007sq\u0000"
+"~\u00001t\u0000\u0006mergedq\u0000~\u0000;sq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q\u0000~\u0000)psq"
+"\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)pq\u0000~\u0000Zq\u0000~\u0000\\q\u0000~\u00007sq\u0000~\u00001t\u0000\u0010GO.go_jaxb.Movedq\u0000~\u0000_s"
+"q\u0000~\u0000\u0000\u0002\u000f\u0096\u00f6pp\u0000sq\u0000~\u0000\u0007\u0002\u000f\u0096\u00ebppsq\u0000~\u0000\u0000\u0000\u00cb\u00f9\u00dfpp\u0000sq\u0000~\u0000$\u0000\u00cb\u00f9\u00d4ppsq\u0000~\u0000U\u0000\u00cb\u00f9\u00c9q"
+"\u0000~\u0000)psq\u0000~\u0000&\u0000\u00cb\u00f9\u00c6q\u0000~\u0000)pq\u0000~\u0000Zq\u0000~\u0000\\q\u0000~\u00007sq\u0000~\u00001t\u0000\u0014GO.go_jaxb.Move"
+"dTypeq\u0000~\u0000_sq\u0000~\u0000$\u0001C\u009d\u0007ppsq\u0000~\u0000&\u0001C\u009c\u00fcq\u0000~\u0000)pq\u0000~\u0000*sq\u0000~\u00001q\u0000~\u00004q\u0000~\u00005q"
+"\u0000~\u00007sq\u0000~\u00001t\u0000\u0005movedq\u0000~\u0000;sq\u0000~\u0000$\u0000\u00b3\u008f\u0089ppsq\u0000~\u0000&\u0000\u00b3\u008f~q\u0000~\u0000)psq\u0000~\u0000\u0010\u0000J~"
+"\u0006ppsr\u0000)com.sun.msv.datatype.xsd.EnumerationFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L"
+"\u0000\u0006valuest\u0000\u000fLjava/util/Set;xr\u00009com.sun.msv.datatype.xsd.DataT"
+"ypeWithValueConstraintFacet\"\u00a7Ro\u00ca\u00c7\u008aT\u0002\u0000\u0000xr\u0000*com.sun.msv.dataty"
+"pe.xsd.DataTypeWithFacet\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0005Z\u0000\fisFacetFixedZ\u0000\u0012needVal"
+"ueCheckFlagL\u0000\bbaseTypet\u0000)Lcom/sun/msv/datatype/xsd/XSDatatyp"
+"eImpl;L\u0000\fconcreteTypet\u0000\'Lcom/sun/msv/datatype/xsd/ConcreteTy"
+"pe;L\u0000\tfacetNameq\u0000~\u0000\u0018xq\u0000~\u0000\u0017q\u0000~\u0000;pq\u0000~\u0000/\u0000\u0000sr\u0000$com.sun.msv.datat"
+"ype.xsd.NmtokenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xr\u0000\"com.sun.msv.datatype.xsd.T"
+"okenType\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0000xq\u0000~\u0000\u0014q\u0000~\u0000\u001bt\u0000\u0007NMTOKENq\u0000~\u0000/\u0000q\u0000~\u0000\u00c5t\u0000\u000benumer"
+"ationsr\u0000\u0011java.util.HashSet\u00baD\u0085\u0095\u0096\u00b8\u00b74\u0003\u0000\u0000xpw\f\u0000\u0000\u0000\u0010?@\u0000\u0000\u0000\u0000\u0000\u0002t\u0000\u0002not\u0000"
+"\u0003yesxq\u0000~\u0000!sq\u0000~\u0000\"t\u0000\u000fNMTOKEN-derivedq\u0000~\u0000;sq\u0000~\u00001t\u0000\bobsoleteq\u0000~\u0000"
+";q\u0000~\u00007sq\u0000~\u0000$\u0002a\u0012#ppsq\u0000~\u0000&\u0002a\u0012\u0018q\u0000~\u0000)pq\u0000~\u0000*sq\u0000~\u00001q\u0000~\u00004q\u0000~\u00005q\u0000~\u00007"
+"sq\u0000~\u00001t\u0000\u0007historyq\u0000~\u0000;sr\u0000\"com.sun.msv.grammar.ExpressionPool\u0000"
+"\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0002\u0000\u0001L\u0000\bexpTablet\u0000/Lcom/sun/msv/grammar/ExpressionPool$"
+"ClosedHash;xpsr\u0000-com.sun.msv.grammar.ExpressionPool$ClosedHa"
+"sh\u00d7j\u00d0N\u00ef\u00e8\u00ed\u001c\u0002\u0000\u0004I\u0000\u0005countI\u0000\tthresholdL\u0000\u0006parentq\u0000~\u0000\u00d6[\u0000\u0005tablet\u0000![L"
+"com/sun/msv/grammar/Expression;xp\u0000\u0000\u00004\u0000\u0000\u00009pur\u0000![Lcom.sun.msv."
+"grammar.Expression;\u00d68D\u00c3]\u00ad\u00a7\n\u0002\u0000\u0000xp\u0000\u0000\u0000\u00bfpppppq\u0000~\u0000>pppppq\u0000~\u0000Rpppp"
+"ppppq\u0000~\u0000=pq\u0000~\u0000Lpppppppppppppq\u0000~\u0000\u009appppppppq\u0000~\u0000Wq\u0000~\u0000dq\u0000~\u0000oq\u0000~\u0000"
+"wq\u0000~\u0000\u0082q\u0000~\u0000hq\u0000~\u0000\u008aq\u0000~\u0000\u0095q\u0000~\u0000\u009dq\u0000~\u0000\u00a8q\u0000~\u0000\u00b0q\u0000~\u0000Tq\u0000~\u0000cq\u0000~\u0000nq\u0000~\u0000vq\u0000~\u0000"
+"\u0081q\u0000~\u0000\u0089q\u0000~\u0000\u0094q\u0000~\u0000\u009cq\u0000~\u0000\u00a7q\u0000~\u0000Pq\u0000~\u0000\u00afq\u0000~\u0000\u008eq\u0000~\u0000Jq\u0000~\u0000\u00b4q\u0000~\u0000\tppppppppp"
+"q\u0000~\u0000Qq\u0000~\u0000\fppppppq\u0000~\u0000%ppq\u0000~\u0000Eq\u0000~\u0000{q\u0000~\u0000Kpq\u0000~\u0000Npppppppq\u0000~\u0000\u000fppq\u0000"
+"~\u0000Dpppppppppppppppq\u0000~\u0000aq\u0000~\u0000\u00d0pppppppppq\u0000~\u0000\nq\u0000~\u0000Oppppq\u0000~\u0000\u0087q\u0000~\u0000"
+"\u000bq\u0000~\u0000\u00adppppppppq\u0000~\u0000\rppppq\u0000~\u0000\u00a1pppppppq\u0000~\u0000tq\u0000~\u0000Mppppppppppppppq"
+"\u0000~\u0000\u00b9ppppppppppp"));
        }
        return new com.sun.msv.verifier.regexp.REDocumentDeclaration(schemaFragment);
    }

    public class Unmarshaller
        extends GO.go_jaxb.impl.runtime.AbstractUnmarshallingEventHandlerImpl
    {


        public Unmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context) {
            super(context, "----");
        }

        protected Unmarshaller(GO.go_jaxb.impl.runtime.UnmarshallingContext context, int startState) {
            this(context);
            state = startState;
        }

        public java.lang.Object owner() {
            return GO.go_jaxb.impl.HistoryImpl.this;
        }

        public void enterElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname, org.xml.sax.Attributes __atts)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterElement(___uri, ___local, ___qname, __atts);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "obsolete");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().enterElement(___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        if (("date" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterElement((((GO.go_jaxb.impl.HistoryTypeImpl)GO.go_jaxb.impl.HistoryImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname, __atts);
                            return ;
                        }
                        break;
                    case  0 :
                        if (("history" == ___local)&&("" == ___uri)) {
                            context.pushAttributes(__atts, false);
                            state = 1;
                            return ;
                        }
                        break;
                }
                super.enterElement(___uri, ___local, ___qname, __atts);
                break;
            }
        }

        public void leaveElement(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveElement(___uri, ___local, ___qname);
                        return ;
                    case  2 :
                        if (("history" == ___local)&&("" == ___uri)) {
                            context.popAttributes();
                            state = 3;
                            return ;
                        }
                        break;
                    case  1 :
                        attIdx = context.getAttribute("", "obsolete");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveElement(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveElement(___uri, ___local, ___qname);
                break;
            }
        }

        public void enterAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromEnterAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        if (("obsolete" == ___local)&&("" == ___uri)) {
                            spawnHandlerFromEnterAttribute((((GO.go_jaxb.impl.HistoryTypeImpl)GO.go_jaxb.impl.HistoryImpl.this).new Unmarshaller(context)), 2, ___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.enterAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void leaveAttribute(java.lang.String ___uri, java.lang.String ___local, java.lang.String ___qname)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                switch (state) {
                    case  3 :
                        revertToParentFromLeaveAttribute(___uri, ___local, ___qname);
                        return ;
                    case  1 :
                        attIdx = context.getAttribute("", "obsolete");
                        if (attIdx >= 0) {
                            context.consumeAttribute(attIdx);
                            context.getCurrentHandler().leaveAttribute(___uri, ___local, ___qname);
                            return ;
                        }
                        break;
                }
                super.leaveAttribute(___uri, ___local, ___qname);
                break;
            }
        }

        public void handleText(final java.lang.String value)
            throws org.xml.sax.SAXException
        {
            int attIdx;
            outer:
            while (true) {
                try {
                    switch (state) {
                        case  3 :
                            revertToParentFromText(value);
                            return ;
                        case  1 :
                            attIdx = context.getAttribute("", "obsolete");
                            if (attIdx >= 0) {
                                context.consumeAttribute(attIdx);
                                context.getCurrentHandler().text(value);
                                return ;
                            }
                            break;
                    }
                } catch (java.lang.RuntimeException e) {
                    handleUnexpectedTextException(value, e);
                }
                break;
            }
        }

    }

}
