//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/khoran/javaPrograms/svnCO/GO/go4.xsd line 125)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}evidence" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}gene_product"/>
 *       &lt;/sequence>
 *       &lt;attribute name="parseType" type="{http://www.w3.org/2001/XMLSchema}string" fixed="Resource" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface AssociationType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.GeneProduct}
     *     {@link GO.go_jaxb.GeneProductType}
     */
    GO.go_jaxb.GeneProductType getGeneProduct();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.GeneProduct}
     *     {@link GO.go_jaxb.GeneProductType}
     */
    void setGeneProduct(GO.go_jaxb.GeneProductType value);

    /**
     * Gets the value of the Evidence property.
     * 
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the Evidence property.
     * 
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEvidence().add(newItem);
     * </pre>
     * 
     * 
     * Objects of the following type(s) are allowed in the list
     * {@link GO.go_jaxb.Evidence}
     * {@link GO.go_jaxb.EvidenceType}
     * 
     */
    java.util.List getEvidence();

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getParseType();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setParseType(java.lang.String value);

}
