//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb;


/**
 * Java content class for go element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/khoran/javaPrograms/svnCO/GO/go4.xsd line 39)
 * <p>
 * <pre>
 * &lt;element name="go">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}version" minOccurs="0"/>
 *           &lt;element ref="{}RDF"/>
 *         &lt;/sequence>
 *         &lt;attribute name="rdf" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.w3.org/1999/02/22-rdf-syntax-ns#" />
 *         &lt;attribute name="go" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.geneontology.org/dtds/go.dtd#" />
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Go
    extends javax.xml.bind.Element, GO.go_jaxb.GoType
{


}
