//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/khoran/javaPrograms/svnCO/GO/go4.xsd line 40)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}version" minOccurs="0"/>
 *         &lt;element ref="{}RDF"/>
 *       &lt;/sequence>
 *       &lt;attribute name="rdf" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.w3.org/1999/02/22-rdf-syntax-ns#" />
 *       &lt;attribute name="go" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.geneontology.org/dtds/go.dtd#" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface GoType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getGo();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setGo(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.VersionType}
     *     {@link GO.go_jaxb.Version}
     */
    GO.go_jaxb.VersionType getVersion();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.VersionType}
     *     {@link GO.go_jaxb.Version}
     */
    void setVersion(GO.go_jaxb.VersionType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    java.lang.String getRdf();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     *     {@link java.lang.String}
     */
    void setRdf(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.RDFType}
     *     {@link GO.go_jaxb.RDF}
     */
    GO.go_jaxb.RDFType getRDF();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.RDFType}
     *     {@link GO.go_jaxb.RDF}
     */
    void setRDF(GO.go_jaxb.RDFType value);

}
