//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/khoran/javaPrograms/svnCO/GO/go4.xsd line 212)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}date"/>
 *         &lt;element ref="{}person"/>
 *         &lt;element ref="{}rationale"/>
 *         &lt;choice>
 *           &lt;element ref="{}created"/>
 *           &lt;element ref="{}deleted"/>
 *           &lt;element ref="{}split"/>
 *           &lt;element ref="{}merged"/>
 *           &lt;element ref="{}moved"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="obsolete">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="yes"/>
 *             &lt;enumeration value="no"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface HistoryType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getRationale();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setRationale(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.SplitType}
     *     {@link GO.go_jaxb.Split}
     */
    GO.go_jaxb.SplitType getSplit();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.SplitType}
     *     {@link GO.go_jaxb.Split}
     */
    void setSplit(GO.go_jaxb.SplitType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.Merged}
     *     {@link GO.go_jaxb.MergedType}
     */
    GO.go_jaxb.MergedType getMerged();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.Merged}
     *     {@link GO.go_jaxb.MergedType}
     */
    void setMerged(GO.go_jaxb.MergedType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.Moved}
     *     {@link GO.go_jaxb.MovedType}
     */
    GO.go_jaxb.MovedType getMoved();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.Moved}
     *     {@link GO.go_jaxb.MovedType}
     */
    void setMoved(GO.go_jaxb.MovedType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getDate();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setDate(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getObsolete();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setObsolete(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.DeletedType}
     *     {@link GO.go_jaxb.Deleted}
     */
    GO.go_jaxb.DeletedType getDeleted();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.DeletedType}
     *     {@link GO.go_jaxb.Deleted}
     */
    void setDeleted(GO.go_jaxb.DeletedType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link GO.go_jaxb.CreatedType}
     *     {@link GO.go_jaxb.Created}
     */
    GO.go_jaxb.CreatedType getCreated();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link GO.go_jaxb.CreatedType}
     *     {@link GO.go_jaxb.Created}
     */
    void setCreated(GO.go_jaxb.CreatedType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getPerson();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setPerson(java.lang.String value);

}
