//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2004.01.30 at 01:01:22 PST 
//


package GO.go_jaxb;


/**
 * Java content class for term element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/home/khoran/javaPrograms/svnCO/GO/go4.xsd line 66)
 * <p>
 * <pre>
 * &lt;element name="term">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}accession"/>
 *           &lt;element ref="{}name"/>
 *           &lt;element ref="{}synonym" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}definition" minOccurs="0"/>
 *           &lt;choice maxOccurs="unbounded" minOccurs="0">
 *             &lt;element ref="{}part_of"/>
 *             &lt;element ref="{}is_a"/>
 *           &lt;/choice>
 *           &lt;element ref="{}dbxref" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}association" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{}history" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;attribute name="n_associations" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *         &lt;attribute name="focus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *               &lt;enumeration value="yes"/>
 *               &lt;enumeration value="no"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/attribute>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 */
public interface Term
    extends javax.xml.bind.Element, GO.go_jaxb.TermType
{


}
